CREATE TABLE streams (
	id INTEGER PRIMARY KEY NOT NULL,
	mpd_url TEXT NOT NULL UNIQUE
);

CREATE TABLE stream_redirects (
	stream_id INTEGER PRIMARY KEY NOT NULL REFERENCES streams ON DELETE CASCADE,
	mpd_url TEXT NOT NULL,
	ingestd_token INTEGER NOT NULL REFERENCES ingestd_tokens ON DELETE CASCADE
);

CREATE TABLE ingestd_tokens (
	id INTEGER PRIMARY KEY NOT NULL,
	stream_id INTEGER NOT NULL REFERENCES streams ON DELETE CASCADE,
	token TEXT NOT NULL UNIQUE
);
