[package]
name = "libsrt-sys"
version = "0.1.0"
authors = ["Shell Turner <shell@alterednarrative.net>"]
edition = "2018"
links = "srt"
build = "build.rs"

[dependencies]
libc = "0.2.73"

[build-dependencies]
pkg-config = "0.3.18"
bindgen = "0.54.1"
